// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBU0WEXIStIewtKNqs1QtqJHBBRT7vtyhA',
    appId: '1:186464110544:web:ed7f2ce9e671751e6a5bd5',
    messagingSenderId: '186464110544',
    projectId: 'training-f7e70',
    authDomain: 'training-f7e70.firebaseapp.com',
    storageBucket: 'training-f7e70.firebasestorage.app',
    measurementId: 'G-FP97CCGCVE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAZPiN9VtFeIw3zPPg9yd5GdJUhA6PVWaQ',
    appId: '1:186464110544:android:6fdfdad8a4a6f0216a5bd5',
    messagingSenderId: '186464110544',
    projectId: 'training-f7e70',
    storageBucket: 'training-f7e70.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDvL6460ViaHOaeVYf-Dp7RxleX31DpYo8',
    appId: '1:186464110544:ios:962d84fd7249ec656a5bd5',
    messagingSenderId: '186464110544',
    projectId: 'training-f7e70',
    storageBucket: 'training-f7e70.firebasestorage.app',
    iosBundleId: 'com.example.training',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDvL6460ViaHOaeVYf-Dp7RxleX31DpYo8',
    appId: '1:186464110544:ios:962d84fd7249ec656a5bd5',
    messagingSenderId: '186464110544',
    projectId: 'training-f7e70',
    storageBucket: 'training-f7e70.firebasestorage.app',
    iosBundleId: 'com.example.training',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBU0WEXIStIewtKNqs1QtqJHBBRT7vtyhA',
    appId: '1:186464110544:web:972e3f826140aab96a5bd5',
    messagingSenderId: '186464110544',
    projectId: 'training-f7e70',
    authDomain: 'training-f7e70.firebaseapp.com',
    storageBucket: 'training-f7e70.firebasestorage.app',
    measurementId: 'G-HEGPSJSNH7',
  );
}
